name: 'Semantic Pull Request'

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
permissions:
  contents: read
jobs:
  main:
    name: Validate PR and Commits
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@0184f5a228ee06430bb9e67d65f73a1a6767496a # v6.2.0
        with:
          configFile: .github/commitlint.config.cjs
      - name: Install Dependencies
        run: npm install @commitlint/config-conventional@17.4.2
      - uses: JulienKode/pull-request-name-linter-action@8c05fb989d9f156ce61e33754f9802c9d3cffa58 # v0.5.0
        with:
          configuration-path: ./.github/commitlint.config.cjs
